# Loading and Updating Data in the Cytoxnet Package

While the cytoxnet package come pre-loaded with a handfull of datasets, you'll probably want to train the models using your own datasets.

The cytoxnet package utilizes sqlite to create a lightweight, portable database for data storage and retreival.  It contains a codex of molecular compounds which is updated with any new smiles strings anytime a new dataset is loaded into the database.

In this notebook, we're look at adding new datasets to the database as well as updating existing datasets when needed.

## Loading Data
Let's start by importing the packages we need to add new data

In [1]:
import cytoxnet.dataprep.featurize as ft
import cytoxnet.dataprep.dataprep as dp
import cytoxnet.data as data
import cytoxnet.dataprep.database as db
import cytoxnet.dataprep.io

In [2]:
import sqlite3
import sqlalchemy
from sqlalchemy import Table, Column, ForeignKey, Integer, String, Float, Boolean, DateTime, Interval, MetaData, create_engine, select, or_, and_, join, union
import pandas as pd
import csv
import os


import os
import pkg_resources

import numpy as np
import pandas as pd
import deepchem as dc

Next, let's create the compound codex.  This is a persistent table which will be updated with new smile strings every time we add a new dataset to the database folder.  It is also where we will store feature objects which we can retreive later.  Saving the feature objects this way saves us computational time since we won't have to generate feature objects every time we want to retreive a dataset.

In [3]:
cytoxnet.dataprep.io.create_compound_codex()

Running the create_compound_codex function before we've added any new datasets will result in an empty csv file, which we cand see by calling the newly generated csv file as a Pandas dataframe.

In [4]:
compounds_df = pd.read_csv('database/compounds.csv')
compounds_df

Empty DataFrame
Columns: [Unnamed: 0, smiles]
Index: []

Now, let's add some new datasets and see what happens.  We'll start by loading in a couple of the datasets which come with the package (the lunghini algea EC50 and daphnia EC50 datasets).  We can load these datasets using the add_datasets function from the io.py file.

After running the add_datasets function, you might notice it takes a while to complete.  Don't worry!  Generating features can take a while.  In this example, we'll run the Circular Fingerprint featurizer since it's one of the more lightweight featurizers.

In [5]:
dataframe_dict = cytoxnet.dataprep.io.add_datasets(['lunghini_algea_EC50', 'lunghini_daphnia_EC50'], names=['algea', 'daphnia'], new_featurizers=['CircularFingerprint'])

The add_datasets function creates a dictionary with table names as the keys and dataframe objects as the values.  Let's take a look at some of the data from the algea dataset which we've named 'algea'.  When you load in your own datasets, you can of course call the datasets anything you want!

In [6]:
dataframe_dict['algea']

,chemical_formula,smiles,casnum,molecular_weight,species,algea_EC50,units,source,foreign_key
0,C10H10Br2O2,BrC(Br)c1ccccc1OCC1CO1,30171-80-3,321.993195,algea,-0.879477,log(mg/L),"NITE, Literature set",0
1,C8H7Br,BrC=Cc1ccccc1,103-64-0,183.045181,algea,3.919991,log(mg/L),ECHA,1
2,C9H15Br6O4P,O=P(OCC(Br)CBr)(OCC(Br)CBr)OCC(Br)CBr,126-72-7,697.610779,algea,0.875469,log(mg/L),"NITE, ECOTOX, OASIS, Literature set",2
3,C9H9Br,BrCC=Cc1ccccc1,4392-24-9,197.071762,algea,2.940220,log(mg/L),Literature set,3
4,C2H4Br2,BrCCBr,106-93-4,187.861160,algea,3.255786,log(mg/L),"ECHA, ECOTOX",4
...,...,...,...,...,...,...,...,...,...
1435,C4H4S,c1ccsc1,110-02-1,84.139557,algea,4.382027,log(mg/L),"NITE, VEGA, Literature set",1435
1436,C7H6N2,c1ccc2[nH]cnc2c1,51-17-2,118.135941,algea,3.288402,log(mg/L),ECHA,1436
1437,C7H5NS,c1ccc2scnc2c1,95-16-9,135.186295,algea,3.885679,log(mg/L),"ECHA, NITE, ECOTOX, OASIS, Literature set, VEGA",1437
1438,C2H3N3,c1nc[nH]n1,288-88-0,69.065323,algea,3.942552,log(mg/L),"ECHA, ECOTOX",1438
1439,C3H3N3,c1ncncn1,290-87-9,81.076019,algea,5.476464,log(mg/L),Literature set,1439

Beyond creating a dataframe dictionary, the add_datasets function updates the compounds codex which we created early all of the new smiles appearing in our algea and daphnia datasets.  It also assigns a unique integer id number to each smiles and generates any feature objects which we specify.  In this example, we have chosen to generate just the circular fingerprints since they are generally small and can be generated relatively quickly, but we could also generate more than one feature at once if we chose.

If we look back at the previously empty compounds codex, we can see now that it has been populated with all our new smiles and circular fingerprint values!

In [7]:
compounds_df = pd.read_csv('database/compounds.csv')
compounds_df

,Unnamed: 0,smiles,CircularFingerprint
0,0,BrC(Br)c1ccccc1OCC1CO1,[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
1,1,BrC=Cc1ccccc1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2,2,O=P(OCC(Br)CBr)(OCC(Br)CBr)OCC(Br)CBr,[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
3,3,BrCC=Cc1ccccc1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
4,4,BrCCBr,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
...,...,...,...
2678,2678,c1ccc2cnccc2c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2679,2679,c1ccc2nc3ccccc3cc2c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2680,2680,c1ccncc1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2681,2681,c1coc(-c2nc3ccccc3[nH]2)c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2682,2682,c1ccc2[nH]c(-c3cscn3)nc2c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...

Before moving on, we should send our updated compounds table into the our persistent database.  Since we're loading in our codex, we'll set the codex parameter to True.

In [9]:
db.table_creator(table_name='compounds', dataframe=compounds_df, codex=True, id_col=None)

2021-06-08 23:38:08,383 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:08,387 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("compounds")
2021-06-08 23:38:08,391 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:08,399 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("compounds")
2021-06-08 23:38:08,402 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:08,408 INFO sqlalchemy.engine.Engine
CREATE TABLE compounds (
	ids INTEGER NOT NULL,
	smiles VARCHAR,
	circularfingerprint VARCHAR,
	PRIMARY KEY (ids)
)


2021-06-08 23:38:08,412 INFO sqlalchemy.engine.Engine [no key 0.00396s] ()
2021-06-08 23:38:08,431 INFO sqlalchemy.engine.Engine COMMIT
2021-06-08 23:38:08,466 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("compounds")
2021-06-08 23:38:08,467 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:08,479 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:08,533 INFO sqlalchemy.engine.Engine INSERT INTO compounds (ids, smiles, circularfingerprint) VALUES (?, ?, ?)
2021-06-08 23:38:08,534 INFO sqlalchemy.engine.Engine [generated in 0.04466s] ((0, 'BrC(Br)c1ccccc1OCC1CO1', '[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (1, 'BrC=Cc1ccccc1', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (2, 'O=P(OCC(Br)CBr)(OCC(Br)CBr)OCC(Br)CBr', '[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (3, 'BrCC=Cc1ccccc1', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (4, 'BrCCBr', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (5, 'BrCCCBr', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (6, 'BrCCCCCCBr', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (7, 'BrCCCCCCCCBr', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]')  ... displaying 10 of 2683 total bound parameter sets ...  (2681, 'c1coc(-c2nc3ccccc3[nH]2)c1', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'), (2682, 'c1ccc2[nH]c(-c3cscn3)nc2c1', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  ... (6017 characters truncated) ...  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0.]'))
2021-06-08 23:38:08,639 INFO sqlalchemy.engine.Engine COMMIT

In order to create persistant instances of our new algea and daphnia datasets, we can load them into the cytoxnet.db database file.  This database is built using sqlite so that you can store the entire database locally.

We'll add our datasets to the database using the table_creator and tables_to_database functions.  The table_creator function takes in a table name and a dataframe object.  We can add load in each table individually...

In [10]:
db.table_creator(table_name='algea', dataframe=dataframe_dict['algea'], codex=False, id_col=None)

2021-06-08 23:38:13,202 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("compounds")
2021-06-08 23:38:13,203 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,206 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:13,208 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:13,214 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("compounds")
2021-06-08 23:38:13,219 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,223 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("compounds")
2021-06-08 23:38:13,226 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,231 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:13,237 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:13,252 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("compounds")
2021-06-08 23:38:13,255 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,257 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("compounds")
2021-06-08 23:38:13,259 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,263 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("compounds")
2021-06-08 23:38:13,264 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,277 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("compounds")
2021-06-08 23:38:13,280 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,284 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:13,288 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:13,330 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:13,332 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("compounds")
2021-06-08 23:38:13,333 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,336 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("algea")
2021-06-08 23:38:13,340 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,343 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("algea")
2021-06-08 23:38:13,346 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,349 INFO sqlalchemy.engine.Engine
CREATE TABLE algea (
	ids INTEGER NOT NULL,
	smiles VARCHAR,
	chemical_formula VARCHAR,
	casnum VARCHAR,
	molecular_weight FLOAT,
	species VARCHAR,
	algea_ec50 FLOAT,
	units VARCHAR,
	source VARCHAR,
	foreign_key INTEGER,
	PRIMARY KEY (ids),
	FOREIGN KEY(foreign_key) REFERENCES compounds (ids)
)


2021-06-08 23:38:13,362 INFO sqlalchemy.engine.Engine [no key 0.01244s] ()
2021-06-08 23:38:13,396 INFO sqlalchemy.engine.Engine COMMIT
2021-06-08 23:38:13,425 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("algea")
2021-06-08 23:38:13,426 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:13,442 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:13,483 INFO sqlalchemy.engine.Engine INSERT INTO algea (ids, smiles, chemical_formula, casnum, molecular_weight, species, algea_ec50, units, source, foreign_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-06-08 23:38:13,484 INFO sqlalchemy.engine.Engine [generated in 0.03127s] ((0, 'BrC(Br)c1ccccc1OCC1CO1', 'C10H10Br2O2', '30171-80-3', 321.9931945800781, 'algea', -0.8794767587514388, 'log(mg/L)', 'NITE, Literature set', 0), (1, 'BrC=Cc1ccccc1', 'C8H7Br', '103-64-0', 183.0451812744141, 'algea', 3.919991175077323, 'log(mg/L)', 'ECHA', 1), (2, 'O=P(OCC(Br)CBr)(OCC(Br)CBr)OCC(Br)CBr', 'C9H15Br6O4P', '126-72-7', 697.6107788085938, 'algea', 0.8754687373538999, 'log(mg/L)', 'NITE, ECOTOX, OASIS, Literature set', 2), (3, 'BrCC=Cc1ccccc1', 'C9H9Br', '4392-24-9', 197.0717620849609, 'algea', 2.9402195636237325, 'log(mg/L)', 'Literature set', 3), (4, 'BrCCBr', 'C2H4Br2', '106-93-4', 187.8611602783203, 'algea', 3.255786178888298, 'log(mg/L)', 'ECHA, ECOTOX', 4), (5, 'BrCCCBr', 'C3H6Br2', '109-64-8', 201.8877410888672, 'algea', 3.555348061489413, 'log(mg/L)', 'NITE, VEGA, Literature set', 5), (6, 'BrCCCCCCBr', 'C6H12Br2', '629-03-8', 243.9674835205078, 'algea', 1.8802281172156632, 'log(mg/L)', 'Literature set', 6), (7, 'BrCCCCCCCCBr', 'C8H16Br2', '4549-32-0', 272.0206298828125, 'algea', 1.3297240096314962, 'log(mg/L)', 'Literature set', 7)  ... displaying 10 of 1440 total bound parameter sets ...  (1438, 'c1nc[nH]n1', 'C2H3N3', '288-88-0', 69.06532287597656, 'algea', 3.942552210462969, 'log(mg/L)', 'ECHA, ECOTOX', 1438), (1439, 'c1ncncn1', 'C3H3N3', '290-87-9', 81.07601928710938, 'algea', 5.476463551931511, 'log(mg/L)', 'Literature set', 1439))
2021-06-08 23:38:13,502 INFO sqlalchemy.engine.Engine COMMIT

... or we can iterate through the dataframe dictionary we created a few cells back using the tables_to_database function.  This function simply calls the table_creator function and iterates through a dictionary object containing table names and dataframe objects.  This is expecially advantagous if we have multiple new datasets we're interested in, since we can quickly load them all into the database using the add_dataset function together with the tables_to_databae function.

In [11]:
db.tables_to_database(dataframe_dict=dataframe_dict)

2021-06-08 23:38:18,634 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("compounds")
2021-06-08 23:38:18,636 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,638 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:18,639 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:18,643 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("compounds")
2021-06-08 23:38:18,644 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,647 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("compounds")
2021-06-08 23:38:18,653 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,658 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:18,662 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:18,667 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("compounds")
2021-06-08 23:38:18,669 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,672 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("compounds")
2021-06-08 23:38:18,674 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,676 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("compounds")
2021-06-08 23:38:18,679 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,683 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("compounds")
2021-06-08 23:38:18,693 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,698 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:18,703 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:18,744 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:18,746 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("compounds")
2021-06-08 23:38:18,748 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,758 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("algea")
2021-06-08 23:38:18,761 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,763 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("algea")
2021-06-08 23:38:18,768 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,774 INFO sqlalchemy.engine.Engine
CREATE TABLE algea (
	ids INTEGER NOT NULL,
	smiles VARCHAR,
	chemical_formula VARCHAR,
	casnum VARCHAR,
	molecular_weight FLOAT,
	species VARCHAR,
	algea_ec50 FLOAT,
	units VARCHAR,
	source VARCHAR,
	foreign_key INTEGER,
	PRIMARY KEY (ids),
	FOREIGN KEY(foreign_key) REFERENCES compounds (ids)
)


2021-06-08 23:38:18,778 INFO sqlalchemy.engine.Engine [no key 0.00428s] ()
2021-06-08 23:38:18,795 INFO sqlalchemy.engine.Engine COMMIT
2021-06-08 23:38:18,846 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("algea")
2021-06-08 23:38:18,848 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,863 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:18,899 INFO sqlalchemy.engine.Engine INSERT INTO algea (ids, smiles, chemical_formula, casnum, molecular_weight, species, algea_ec50, units, source, foreign_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-06-08 23:38:18,901 INFO sqlalchemy.engine.Engine [generated in 0.03072s] ((0, 'BrC(Br)c1ccccc1OCC1CO1', 'C10H10Br2O2', '30171-80-3', 321.9931945800781, 'algea', -0.8794767587514388, 'log(mg/L)', 'NITE, Literature set', 0), (1, 'BrC=Cc1ccccc1', 'C8H7Br', '103-64-0', 183.0451812744141, 'algea', 3.919991175077323, 'log(mg/L)', 'ECHA', 1), (2, 'O=P(OCC(Br)CBr)(OCC(Br)CBr)OCC(Br)CBr', 'C9H15Br6O4P', '126-72-7', 697.6107788085938, 'algea', 0.8754687373538999, 'log(mg/L)', 'NITE, ECOTOX, OASIS, Literature set', 2), (3, 'BrCC=Cc1ccccc1', 'C9H9Br', '4392-24-9', 197.0717620849609, 'algea', 2.9402195636237325, 'log(mg/L)', 'Literature set', 3), (4, 'BrCCBr', 'C2H4Br2', '106-93-4', 187.8611602783203, 'algea', 3.255786178888298, 'log(mg/L)', 'ECHA, ECOTOX', 4), (5, 'BrCCCBr', 'C3H6Br2', '109-64-8', 201.8877410888672, 'algea', 3.555348061489413, 'log(mg/L)', 'NITE, VEGA, Literature set', 5), (6, 'BrCCCCCCBr', 'C6H12Br2', '629-03-8', 243.9674835205078, 'algea', 1.8802281172156632, 'log(mg/L)', 'Literature set', 6), (7, 'BrCCCCCCCCBr', 'C8H16Br2', '4549-32-0', 272.0206298828125, 'algea', 1.3297240096314962, 'log(mg/L)', 'Literature set', 7)  ... displaying 10 of 1440 total bound parameter sets ...  (1438, 'c1nc[nH]n1', 'C2H3N3', '288-88-0', 69.06532287597656, 'algea', 3.942552210462969, 'log(mg/L)', 'ECHA, ECOTOX', 1438), (1439, 'c1ncncn1', 'C3H3N3', '290-87-9', 81.07601928710938, 'algea', 5.476463551931511, 'log(mg/L)', 'Literature set', 1439))
2021-06-08 23:38:18,922 INFO sqlalchemy.engine.Engine COMMIT
2021-06-08 23:38:18,964 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("compounds")
2021-06-08 23:38:18,970 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:18,982 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:18,992 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:18,995 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("compounds")
2021-06-08 23:38:18,997 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,008 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("compounds")
2021-06-08 23:38:19,018 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,023 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:19,026 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:19,031 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("compounds")
2021-06-08 23:38:19,037 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,044 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("compounds")
2021-06-08 23:38:19,048 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,052 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("compounds")
2021-06-08 23:38:19,055 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,060 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("compounds")
2021-06-08 23:38:19,061 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,064 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2021-06-08 23:38:19,066 INFO sqlalchemy.engine.Engine [raw sql] ('compounds',)
2021-06-08 23:38:19,081 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:19,083 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("compounds")
2021-06-08 23:38:19,088 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,092 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("daphnia")
2021-06-08 23:38:19,094 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,112 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("daphnia")
2021-06-08 23:38:19,116 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,122 INFO sqlalchemy.engine.Engine
CREATE TABLE daphnia (
	ids INTEGER NOT NULL,
	smiles VARCHAR,
	chemical_formula VARCHAR,
	casnum VARCHAR,
	molecular_weight FLOAT,
	species VARCHAR,
	daphnia_ec50 FLOAT,
	units VARCHAR,
	source VARCHAR,
	foreign_key INTEGER,
	PRIMARY KEY (ids),
	FOREIGN KEY(foreign_key) REFERENCES compounds (ids)
)


2021-06-08 23:38:19,124 INFO sqlalchemy.engine.Engine [no key 0.00202s] ()
2021-06-08 23:38:19,150 INFO sqlalchemy.engine.Engine COMMIT
2021-06-08 23:38:19,176 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("daphnia")
2021-06-08 23:38:19,177 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-08 23:38:19,186 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-08 23:38:19,266 INFO sqlalchemy.engine.Engine INSERT INTO daphnia (ids, smiles, chemical_formula, casnum, molecular_weight, species, daphnia_ec50, units, source, foreign_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

2021-06-08 23:38:19,269 INFO sqlalchemy.engine.Engine [generated in 0.07002s] ((0, 'C=C(Br)c1ccccc1', 'C8H7Br', '98-81-7', 183.0451812744141, 'daphnia', -1.1086626245216111, 'log(mg/L)', 'NITE, VEGA, Literature set', 1440), (1, 'BrC(Br)Br', 'CHBr3', '75252', 252.7306365966797, 'daphnia', 3.828361036331304, 'log(mg/L)', 'ECOTOX, OASIS, VEGA, Literature set', 1441), (2, 'BrC(Br)c1ccccc1OCC1CO1', 'C10H10Br2O2', '30171-80-3', 321.9931945800781, 'daphnia', 0.262364264467491, 'log(mg/L)', 'NITE, Literature set', 0), (3, 'BrC1CCCCC1', 'C6H11Br', '108850', 163.0555419921875, 'daphnia', 3.044522437723423, 'log(mg/L)', 'ECOTOX, OASIS, VEGA, Literature set', 1442), (4, 'BrC=C(Br)Br', 'C2HBr3', '598163', 264.7413330078125, 'daphnia', 2.516264483437345, 'log(mg/L)', 'ECOTOX, OASIS, VEGA, Literature set', 1443), (5, 'BrC=Cc1ccccc1', 'C8H7Br', '103-64-0', 183.0451812744141, 'daphnia', 1.8082887711792648, 'log(mg/L)', 'ECHA', 1), (6, 'N#CCCC(Br)(C#N)CBr', 'C6H6Br2N2', '35691-65-7', 265.9332275390625, 'daphnia', 0.1257512053055604, 'log(mg/L)', 'VEGA, Literature set', 1444), (7, 'O=P(OCC(Br)CBr)(OCC(Br)CBr)OCC(Br)CBr', 'C9H15Br6O4P', '126-72-7', 697.6107788085938, 'daphnia', 1.4350845252893227, 'log(mg/L)', 'NITE, ECOTOX, OASIS, Literature set', 2)  ... displaying 10 of 2107 total bound parameter sets ...  (2105, 'c1ccc2scnc2c1', 'C7H5NS', '95-16-9', 135.18629455566406, 'daphnia', 2.9444389791664403, 'log(mg/L)', 'ECHA, NITE, ECOTOX, OASIS, Literature set, VEGA', 1437), (2106, 'c1nc[nH]n1', 'C2H3N3', '288-88-0', 69.06532287597656, 'daphnia', 5.061328408411774, 'log(mg/L)', 'ECHA, ECOTOX', 1438))
2021-06-08 23:38:19,300 INFO sqlalchemy.engine.Engine COMMIT

Any time you make updates to your csv files or want to add a new one to train your model with, all you need to do is execute these few steps, and the cytoxnet database will automatically update the compounds codex file and add all the data to the persistant database!

## Querying
Now let's retrieve the data that we just put into the database.

In [12]:
queried_dataframe = db.query_to_dataframe(tables=['daphnia', 'algea'], features_list='circularfingerprint')
queried_dataframe

/Users/Rory/opt/miniconda3/envs/cytoxnet/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py:362: SAWarning: SELECT statement has a cartesian product between FROM element(s) "daphnia", "algea" and FROM element "compounds".  Apply join condition(s) between each element to resolve.
  util.warn(message)

,daphnia_ids,daphnia_chemical_formula,daphnia_casnum,daphnia_molecular_weight,daphnia_species,daphnia_daphnia_ec50,daphnia_units,daphnia_source,daphnia_foreign_key,algea_ids,algea_chemical_formula,algea_casnum,algea_molecular_weight,algea_species,algea_algea_ec50,algea_units,algea_source,algea_foreign_key,smiles,circularfingerprint
0,0,C8H7Br,98-81-7,183.045181,daphnia,-1.108663,log(mg/L),"NITE, VEGA, Literature set",1440,NaN,None,None,NaN,None,NaN,None,None,NaN,C=C(Br)c1ccccc1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
1,1,CHBr3,75252,252.730637,daphnia,3.828361,log(mg/L),"ECOTOX, OASIS, VEGA, Literature set",1441,NaN,None,None,NaN,None,NaN,None,None,NaN,BrC(Br)Br,[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2,2,C10H10Br2O2,30171-80-3,321.993195,daphnia,0.262364,log(mg/L),"NITE, Literature set",0,0.0,C10H10Br2O2,30171-80-3,321.993195,algea,-0.879477,log(mg/L),"NITE, Literature set",0.0,BrC(Br)c1ccccc1OCC1CO1,[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
3,3,C6H11Br,108850,163.055542,daphnia,3.044522,log(mg/L),"ECOTOX, OASIS, VEGA, Literature set",1442,NaN,None,None,NaN,None,NaN,None,None,NaN,BrC1CCCCC1,[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
4,4,C2HBr3,598163,264.741333,daphnia,2.516264,log(mg/L),"ECOTOX, OASIS, VEGA, Literature set",1443,NaN,None,None,NaN,None,NaN,None,None,NaN,BrC=C(Br)Br,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,2102,C11H8N2O,3878-19-1,184.194016,daphnia,1.547563,log(mg/L),EFSA,2681,NaN,None,None,NaN,None,NaN,None,None,NaN,c1coc(-c2nc3ccccc3[nH]2)c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2103,2103,C10H7N3S,148-79-8,201.247681,daphnia,-1.814005,log(mg/L),"VEGA, Literature set",2682,NaN,None,None,NaN,None,NaN,None,None,NaN,c1ccc2[nH]c(-c3cscn3)nc2c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2104,2104,C7H6N2,51-17-2,118.135941,daphnia,4.016383,log(mg/L),ECHA,1436,1436.0,C7H6N2,51-17-2,118.135941,algea,3.288402,log(mg/L),ECHA,1436.0,c1ccc2[nH]cnc2c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2105,2105,C7H5NS,95-16-9,135.186295,daphnia,2.944439,log(mg/L),"ECHA, NITE, ECOTOX, OASIS, Literature set, VEGA",1437,1437.0,C7H5NS,95-16-9,135.186295,algea,3.885679,log(mg/L),"ECHA, NITE, ECOTOX, OASIS, Literature set, VEGA",1437.0,c1ccc2scnc2c1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...
2106,2106,C2H3N3,288-88-0,69.065323,daphnia,5.061328,log(mg/L),"ECHA, ECOTOX",1438,1438.0,C2H3N3,288-88-0,69.065323,algea,3.942552,log(mg/L),"ECHA, ECOTOX",1438.0,c1nc[nH]n1,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...